module.exports = {
    FETCH_NOTES: 'FETCH_NOTES',
    GET_CURRENT_NOTE: 'GET_CURRENT_NOTE',
    CLEAR_CURRENT_NOTE: 'CLEAR_CURRENT_NOTE',
    ADD_NOTE: 'ADD_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    DELETE_NOTE: 'DELETE_NOTE',

    FETCH_DOCUMENTS: 'FETCH_DOCUMENTS',
    ADD_DOCUMENT: 'ADD_DOCUMENT',
    DELETE_DOCUMENT: 'DELETE_NOTE',

    SET_CURRENT_FILE: 'SET_CURRENT_FILE',
    CLEAR_CURRENT_FILE: 'CLEAR_CURRENT_FILE',
    UPLOAD_FILE: 'UPLOAD_FILE',
    DELETE_FILE: 'DELETE_FILE',
    SET_DROPPED_FILE: 'SET_DROPPED_FILE',
    CLEAR_DROPPED_FILE: 'CLEAR_DROPPED_FILE',

    FETCH_BOOKS: 'FETCH_BOOKS',
    GET_CURRENT_BOOK: 'GET_CURRENT_BOOKS',
    CLEAR_CURRENT_BOOK: 'CLEAR_CURRENT_BOOKS',
    ADD_BOOK: 'ADD_BOOK',
    EDIT_BOOK: 'EDIT_BOOK',
    DELETE_BOOK: 'DELETE_BOOK',
}