module.exports = {
    FETCH_NOTES: 'FETCH_NOTES',
    GET_CURRENT_NOTE: 'GET_CURRENT_NOTE',
    CLEAR_CURRENT_NOTE: 'CLEAR_CURRENT_NOTE',
    ADD_NOTE: 'ADD_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    DELETE_NOTE: 'DELETE_NOTE'
}