module.exports = {
    FETCH_NOTES: 'FETCH_NOTES',
    GET_CURRENT_NOTE: 'GET_CURRENT_NOTE',
    CLEAR_CURRENT_NOTE: 'CLEAR_CURRENT_NOTE',
    ADD_NOTE: 'ADD_NOTE',
    EDIT_NOTE: 'EDIT_NOTE',
    DELETE_NOTE: 'DELETE_NOTE',

    FETCH_DOCUMENTS: 'FETCH_DOCUMENTS',
    GET_CURRENT_DOCUMENT: 'GET_CURRENT_DOCUMENT',
    CLEAR_CURRENT_DOCUMENT: 'CLEAR_CURRENT_DOCUMENT',
    ADD_DOCUMENT: 'ADD_DOCUMENT',
    EDIT_DOCUMENT: 'EDIT_DOCUMENT',
    DELETE_DOCUMENT: 'DELETE_NOTE',

    SET_CURRENT_FILE: 'SET_CURRENT_FILE',
    CLEAR_CURRENT_FILE: 'CLEAR_CURRENT_FILE'
}